---
kind: pipeline
type: exec
name: build

steps:
- name: build-8.1
  commands:
    - make only-8.1
- name: build-8.2
  commands:
    - make only-8.2
- name: build-8.3
  commands:
    - make only-8.3
- name: build-8.4
  commands:
    - make only-8.4

- name: push-remote
  environment:
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN_AKESTER
  commands:
    - make push-remote

  when:
      branch:
        - master