---
kind: pipeline
type: exec
name: build

concurrency:
  limit: 1

steps:
- name: build
  commands:
    - make

- name: push-remote
  environment:
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN_AKESTER
  commands:
    - make push-remote

  when:
      branch:
        - master