variables:
  PKR_VAR_container_version: $CI_COMMIT_BRANCH
  PKR_VAR_php_version: "8.3"

stages:
  - build
  - deploy

bolt:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/akester/puppet
  variables:
    BOLT_PROJECT: '/builds/containers/php'
  script:
    - bolt module install
  artifacts:
    paths:
      - .modules/
      - .resource_types/
    expire_in: 7 days

build-x86:
  stage: build
  needs:
    - job: bolt
      artifacts: true
  tags:
    - exec
  script:
    - make build-x86
    - make push-x86

build-arm:
  stage: build
  needs:
    - job: bolt
      artifacts: true
  tags:
    - exec-arm
  script:
    - make build-arm
    - make push-arm

push-manifest:
  stage: deploy
  tags:
    - exec
  dependencies:
    - build-x86
    - build-arm
  script:
    - make push-manifest
